### ISSUE TITLE
Compilation error: 'startAdvertising' is not a member of 'BLEDevice'

### ISSUE THREAD

**Issue by FilipeFaria90** [arduino-libraries/ArduinoBLE#286] opened 2023-02-06 08:28 UTC
Hello, the issue started in [https://github.com/arduino-libraries/ArduinoBLE/issues/285](https://github.com/arduino-libraries/ArduinoBLE/issues/285)

The issue is closed and I'm not getting an answer so I'll post it again.

I compile the file I have this log:

Compilation error: `'startAdvertising' is not a member of 'BLEDevice'`

```text
In file included from C:\Users\fimartin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\BLE\src/BLECharacteristic.h:17,
from C:\Users\fimartin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\BLE\src/BLEService.h:15,
from C:\Users\fimartin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\BLE\src/BLEClient.h:20,
from C:\Users\fimartin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\BLE\src/BLEUtils.h:16,
from C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:15:
C:\Users\fimartin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\BLE\src/BLEDescriptor.h:25:7: error: redefinition of 'class BLEDescriptor'
class BLEDescriptor {
^~~~~~~~~~~~~
In file included from c:\Users\fimartin\Documents\Arduino\libraries\ArduinoBLE\src/BLECharacteristic.h:25,
from c:\Users\fimartin\Documents\Arduino\libraries\ArduinoBLE\src/BLEService.h:23,
from c:\Users\fimartin\Documents\Arduino\libraries\ArduinoBLE\src/BLEDevice.h:25,
from C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:14:
c:\Users\fimartin\Documents\Arduino\libraries\ArduinoBLE\src/BLEDescriptor.h:28:7: note: previous definition of 'class BLEDescriptor'
class BLEDescriptor {
^~~~~~~~~~~~~
In file included from C:\Users\fimartin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\BLE\src/BLEService.h:15,
from C:\Users\fimartin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\BLE\src/BLEClient.h:20,
from C:\Users\fimartin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\BLE\src/BLEUtils.h:16,
from C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:15:
C:\Users\fimartin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\BLE\src/BLECharacteristic.h:53:7: error: redefinition of 'class BLECharacteristic'
class BLECharacteristic {
^~~~~~~~~~~~~~~~~
In file included from c:\Users\fimartin\Documents\Arduino\libraries\ArduinoBLE\src/BLEService.h:23,
from c:\Users\fimartin\Documents\Arduino\libraries\ArduinoBLE\src/BLEDevice.h:25,
from C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:14:
c:\Users\fimartin\Documents\Arduino\libraries\ArduinoBLE\src/BLECharacteristic.h:45:7: note: previous definition of 'class BLECharacteristic'
class BLECharacteristic {
^~~~~~~~~~~~~~~~~
In file included from C:\Users\fimartin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\BLE\src/BLEClient.h:20,
from C:\Users\fimartin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\BLE\src/BLEUtils.h:16,
from C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:15:
C:\Users\fimartin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\BLE\src/BLEService.h:49:7: error: redefinition of 'class BLEService'
class BLEService {
^~~~~~~~~~
In file included from c:\Users\fimartin\Documents\Arduino\libraries\ArduinoBLE\src/BLEDevice.h:25,
from C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:14:
c:\Users\fimartin\Documents\Arduino\libraries\ArduinoBLE\src/BLEService.h:28:7: note: previous definition of 'class BLEService'
class BLEService {
^~~~~~~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino: In member function 'virtual void SecurityCallback::onAuthenticationComplete(esp_ble_auth_cmpl_t)':
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:134:18: error: 'startAdvertising' is not a member of 'BLEDevice'
BLEDevice::startAdvertising();
^~~~~~~~~~~~~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino: In member function 'virtual void MyCallbacks1::onWrite(BLECharacteristic*)':
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:169:46: error: 'class BLECharacteristic' has no member named 'getValue'; did you mean 'setValue'?
std::string value = pCharacteristic_1->getValue();
^~~~~~~~
setValue
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino: In function 'void setup()':
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:250:14: error: 'init' is not a member of 'BLEDevice'
BLEDevice::init(nameAndModel.c_str());
^~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:251:14: error: 'setEncryptionLevel' is not a member of 'BLEDevice'
BLEDevice::setEncryptionLevel(ESP_BLE_SEC_ENCRYPT);
^~~~~~~~~~~~~~~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:252:14: error: 'setSecurityCallbacks' is not a member of 'BLEDevice'
BLEDevice::setSecurityCallbacks(new SecurityCallback());
^~~~~~~~~~~~~~~~~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:254:24: error: 'createServer' is not a member of 'BLEDevice'
pServer = BLEDevice::createServer();
^~~~~~~~~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:256:33: error: 'class BLEService' has no member named 'createCharacteristic'; did you mean 'addCharacteristic'?
pCharacteristic_1 = pService->createCharacteristic(
^~~~~~~~~~~~~~~~~~~~
addCharacteristic
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:258:44: error: 'PROPERTY_WRITE' is not a member of 'BLECharacteristic'
BLECharacteristic::PROPERTY_WRITE
^~~~~~~~~~~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:260:33: error: 'class BLEService' has no member named 'createCharacteristic'; did you mean 'addCharacteristic'?
pCharacteristic_2 = pService->createCharacteristic(
^~~~~~~~~~~~~~~~~~~~
addCharacteristic
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:262:44: error: 'PROPERTY_READ' is not a member of 'BLECharacteristic'
BLECharacteristic::PROPERTY_READ |
^~~~~~~~~~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:263:44: error: 'PROPERTY_NOTIFY' is not a member of 'BLECharacteristic'
BLECharacteristic::PROPERTY_NOTIFY
^~~~~~~~~~~~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:265:33: error: 'class BLEService' has no member named 'createCharacteristic'; did you mean 'addCharacteristic'?
pCharacteristic_3 = pService->createCharacteristic(
^~~~~~~~~~~~~~~~~~~~
addCharacteristic
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:267:44: error: 'PROPERTY_READ' is not a member of 'BLECharacteristic'
BLECharacteristic::PROPERTY_READ |
^~~~~~~~~~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:268:44: error: 'PROPERTY_NOTIFY' is not a member of 'BLECharacteristic'
BLECharacteristic::PROPERTY_NOTIFY
^~~~~~~~~~~~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:270:22: error: 'class BLECharacteristic' has no member named 'setAccessPermissions'
pCharacteristic_1->setAccessPermissions(ESP_GATT_PERM_READ | ESP_GATT_PERM_WRITE);
^~~~~~~~~~~~~~~~~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:271:22: error: 'class BLECharacteristic' has no member named 'setAccessPermissions'
pCharacteristic_2->setAccessPermissions(ESP_GATT_PERM_READ | ESP_GATT_PERM_WRITE);
^~~~~~~~~~~~~~~~~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:272:22: error: 'class BLECharacteristic' has no member named 'setAccessPermissions'
pCharacteristic_3->setAccessPermissions(ESP_GATT_PERM_READ | ESP_GATT_PERM_WRITE);
^~~~~~~~~~~~~~~~~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:273:52: error: no matching function for call to 'BLECharacteristic::addDescriptor(BLE2902*)'
pCharacteristic_2 -> addDescriptor(new BLE2902());//Habilites Notify
^
In file included from c:\Users\fimartin\Documents\Arduino\libraries\ArduinoBLE\src/BLEService.h:23,
from c:\Users\fimartin\Documents\Arduino\libraries\ArduinoBLE\src/BLEDevice.h:25,
from C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:14:
c:\Users\fimartin\Documents\Arduino\libraries\ArduinoBLE\src/BLECharacteristic.h:91:8: note: candidate: 'void BLECharacteristic::addDescriptor(BLEDescriptor&)'
void addDescriptor(BLEDescriptor& descriptor);
^~~~~~~~~~~~~
c:\Users\fimartin\Documents\Arduino\libraries\ArduinoBLE\src/BLECharacteristic.h:91:8: note: no known conversion for argument 1 from 'BLE2902*' to 'BLEDescriptor&'
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:274:52: error: no matching function for call to 'BLECharacteristic::addDescriptor(BLE2902*)'
pCharacteristic_3 -> addDescriptor(new BLE2902());//Habilites Notify
^
In file included from c:\Users\fimartin\Documents\Arduino\libraries\ArduinoBLE\src/BLEService.h:23,
from c:\Users\fimartin\Documents\Arduino\libraries\ArduinoBLE\src/BLEDevice.h:25,
from C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:14:
c:\Users\fimartin\Documents\Arduino\libraries\ArduinoBLE\src/BLECharacteristic.h:91:8: note: candidate: 'void BLECharacteristic::addDescriptor(BLEDescriptor&)'
void addDescriptor(BLEDescriptor& descriptor);
^~~~~~~~~~~~~
c:\Users\fimartin\Documents\Arduino\libraries\ArduinoBLE\src/BLECharacteristic.h:91:8: note: no known conversion for argument 1 from 'BLE2902*' to 'BLEDescriptor&'
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:276:22: error: 'class BLECharacteristic' has no member named 'setCallbacks'
pCharacteristic_1->setCallbacks(new MyCallbacks1());
^~~~~~~~~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:277:22: error: 'class BLECharacteristic' has no member named 'setCallbacks'
pCharacteristic_2->setCallbacks(new MyCallbacks2());
^~~~~~~~~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:278:22: error: 'class BLECharacteristic' has no member named 'setCallbacks'
pCharacteristic_3->setCallbacks(new MyCallbacks3());
^~~~~~~~~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:279:13: error: 'class BLEService' has no member named 'start'
pService->start();
^~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:280:45: error: 'getAdvertising' is not a member of 'BLEDevice'
BLEAdvertising *pAdvertising = BLEDevice::getAdvertising();
^~~~~~~~~~~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:286:14: error: 'startAdvertising' is not a member of 'BLEDevice'
BLEDevice::startAdvertising();
^~~~~~~~~~~~~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino: In function 'void loop()':
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:431:26: error: 'class BLECharacteristic' has no member named 'notify'
pCharacteristic_3->notify();
^~~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:436:26: error: 'class BLECharacteristic' has no member named 'notify'
pCharacteristic_3->notify();
^~~~~~
C:\Users\fimartin\Documents\Repo_GIT\esp32_BLE\esp32_BLE.ino:460:26: error: 'class BLECharacteristic' has no member named 'notify'
pCharacteristic_2->notify();
^~~~~~
Se encontraron varias bibliotecas para "BLEDevice.h"
Usado: C:\Users\fimartin\Documents\Arduino\libraries\ArduinoBLE
No utilizado: C:\Users\fimartin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\libraries\BLE
exit status 1

Compilation error: 'startAdvertising' is not a member of 'BLEDevice'
```

Do I have to change something in the code?

**Comment by per1234** [comment] 2023-02-06 09:09
Closing as duplicate of https://github.com/arduino-libraries/ArduinoBLE/issues/285

@FilipeFaria90 this is not an appropriate place to request assistance with your project. This is a place to submit formal reports of defects or propose enhancements to the codebase hosted in this repository. The errors you are getting are caused by problems in the code you wrote and we will not help you with that here because it is off topic for this issue tracker.

**Closed by per1234** 2023-02-06 09:09 UTC
Labels: conclusion: duplicate, conclusion: invalid, topic: code
